---
title: "Lab 10 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.

## Warm-up
1. Please load the homerange data `Tamburelloetal_HomeRangeDatabase.csv`
2. Show the min, mean, and max log10.mass by taxonomic class in the dataset.
3. Make a plot that best summarizes this output.

```{r}
library("tidyverse")
```
```{r}
library("janitor")
```


```{r}
homerange <- read_csv("data/Tamburelloetal_HomeRangeDatabase.csv", na="999") %>%  clean_names()
homerange
```


```{r}
homerange_stat <- homerange %>% 
  group_by(class) %>% 
  summarise(mean_log10.mass=mean(log10_mass),
            min_log10.mass=min(log10_mass),
            max_log10.mass=max(log10_mass))
homerange_stat
```

```{r}
homerange %>% 
ggplot(mapping = aes(x=class,y=log10_mass)) + geom_col()
```













































